name: Build Chess Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            visual_studio: "Visual Studio 17 2022"
          - os: windows-2019
            visual_studio: "Visual Studio 16 2019"
    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S src

    - name: Build
      run: cmake --build build --config Release

    - name: Run
      run: .\build\Release\ChessBot 

